site_name: Genesis Code Documentation
nav:
  - Home: index.md
  - Install: install.md
  - Commands: commands.md
  - Debug: debug.md
  - TMX: tmx.md
  - Bitmap Viewer: bitmap.md
  - Other Features: otherfeatures.md
theme: readthedocs